spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: # your url
    username: # your username
    password: # your password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: warn
    com.sun: info
  file: log/blog-pro.log
server:
  port: 8081

